[config]

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.foot]
input_path = "~/.config/matugen/templates/foot-colors.ini"
output_path = "~/.config/foot/themes/matugen"

[templates.niri]
input_path = "~/.config/matugen/templates/niri_layout.kdl"
output_path = "~/.config/niri/layout.kdl"

[templates.mangowc]
input_path = "~/.config/matugen/templates/mangowc.conf"
output_path = "~/.config/mango/colors.conf"

[templates.clipmenu_niri]
input_path = "~/.config/matugen/templates/clipmenu.sh"
output_path = "~/.config/niri/scripts/clipmenu.sh"

[templates.audioswitch_niri]
input_path = "~/.config/matugen/templates/audioswitch.sh"
output_path = "~/.config/niri/scripts/audioswitch.sh"

[templates.powermenu_niri]
input_path = "~/.config/matugen/templates/powermenu.sh"
output_path = "~/.config/niri/scripts/powermenu.sh"

[templates.appmenu_niri]
input_path = "~/.config/matugen/templates/appmenu.sh"
output_path = "~/.config/niri/scripts/appmenu.sh"

[templates.clipmenu_mangowc]
input_path = "~/.config/matugen/templates/clipmenu.sh"
output_path = "~/.config/mango/scripts/clipmenu.sh"

[templates.audioswitch_mangowc]
input_path = "~/.config/matugen/templates/audioswitch.sh"
output_path = "~/.config/mango/scripts/audioswitch.sh"

[templates.powermenu_mangowc]
input_path = "~/.config/matugen/templates/powermenu.sh"
output_path = "~/.config/mango/scripts/powermenu.sh"

[templates.appmenu_mangowc]
input_path = "~/.config/matugen/templates/appmenu.sh"
output_path = "~/.config/mango/scripts/appmenu.sh"

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.helix]
input_path = '~/.config/matugen/templates/helix.toml'
output_path = '~/.config/helix/themes/matugen.toml'
