pad=3x3

[main]
font=Cascadia Code:style=SemiBold:size=10
font-bold=Cascadia Code:style=Bold:size=10
font-italic=Cascadia Code:style=Italic:size=10
include=~/.config/foot/themes/gruvbox-dark
# include=~/.config/foot/themes/matugen.ini

[scrollback]
lines=3000
multiplier=3.0

[key-bindings]
# Spawn new Foot instance
spawn-terminal=Control+Return
