[general]
import = [
  "~/.config/alacritty/key_bindings.toml",
  "~/.config/alacritty/gruvbox_theme.toml",
]

[window]
padding.x = 3
dynamic_padding = false

[font]
size = 10
offset.x = 0
offset.y = 0
glyph_offset.x = 0

[font.bold]
family = "Cascadia Code"
style = "Bold"

[font.italic]
family = "Cascadia Code"
style = "Italic"

[font.normal]
family = "Cascadia Code"
style = "SemiBold"

[scrolling]
history = 3000
multiplier = 3

