- hosts: localhost
  tasks:
    - name: Install required packages
      become: yes
      command: xbps-install "{{item}}"
      loop:
        - qtile
        - pavucontrol
        - btop
        - fuse
        - stow
        - xsel
        - xfce4-screenshooter
        - podman
        - podman-compose
        - gst-plugins-bad1
        - openvpn
        - gcc
        - git
        - NetworkManager
        - ddcutil
        - ffmpeg
        - slock
        - bleachbit
        - wget
        # - pamixer
        - xinit
        - xorg-minimal
        - xorg-server
        - xcb-util-image
        - dmenu
        - sxiv
        - unzip
        - xdg-util
        - noto-fonts-ttf
        - picom
        - python3-psutil
        - xrandr
        - pipeware
        - xwallpaper
        - curl
        - dbus

    - name: Stow dotfiles
      shell: |
        mkdir -p "{{ ansible_env.HOME }}/.librewolf"
        stow --adopt .
      args:
        chdir: "{{ ansible_env.HOME }}/dotfiles"

    - name: Download and install AM
      become: yes
      shell: |
        wget https://raw.githubusercontent.com/ivan-hc/AM/main/INSTALL -O /tmp/AM-INSTALL &&
        chmod a+x /tmp/AM-INSTALL &&
        /tmp/AM-INSTALL &&
        rm /tmp/AM-INSTALL
      args:
        creates: /usr/local/bin/am
    - name: Install AM packages
      command: am -i "{{item}}"
      loop:
        - bruno
        - helix
        - librewolf
        - localsend
        - obs-studio
        - smplayer
        - yazi
        - zen-browser

    - name: Change screen brightness script
      become: yes
      command: ln -s {{ ansible_env.HOME }}/.local/bin/setbrightness.sh /usr/local/bin/setbrightness

    - name: Start NetworkManager
      become: yes
      shell: |
       ln -s /etc/sv/NetworkManager /var/service/ &&
       sv start NetworkManager

    - name: Start dbus
      become: yes
      shell: |
       ln -s /etc/sv/dbus /var/service/ &&
       sv start dbus

    - name: Configure default font
      become: yes
      command: ln -s ~/.config/fontconfig/conf.d/52-my-default-fonts.conf /etc/fonts/conf.d/52-my-default-fonts.conf

    - name: Remove unwanted packages
      become: yes
      command: xbps-remove -Ry "{{item}}"
      loop:
        - linux-firmware-amd
        - geoclue2
        - python3-devel
        - python3-botocore
        - python3-virtualenv
        - pcmanfm
        - python3-pip
        - ImageMagick
        - upower
        - ModemManager
        - libmbim
        - plymouth
        - smartmontools
        - pcsc-lite
        - nano
        - fprintd
        - hunspell-en-GB
        - abrt*
        - lightdm
        - lightdm-gtk-greeter
        - cronie
        - gssproxy
