- hosts: localhost
  tasks:
    - name: Change screen brightness script
      become: yes
      command: ln -s {{ ansible_env.HOME }}/.local/bin/setbrightness.sh /usr/local/bin/setbrightness

    - name: Start dbus
      become: yes
      ansible.builtin.file:
        src: /etc/sv/dbus
        dest: /var/service/dbus
        state: link
      service:
        name: dbus
        state: started

    - name: Start NetworkManager
      become: yes
      ansible.builtin.file:
        src: /etc/sv/NetworkManager
        dest: /var/service/NetworkManager
        state: link
      service:
        name: NetworkManager
        state: started

    - name: Configure default font
      become: yes
      shell: |
        ln -s ~/.config/fontconfig/conf.d/52-my-default-fonts.conf /etc/fonts/conf.d/52-my-default-fonts.conf &&
        fc-cache -f

    - name: Configure root user shell to bash
      become: yes
      command: chsh -s /bin/bash root

    - name: Run zzz, reboot, poweroff without root password
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: '{{ lookup("ansible.builtin.env", "USER") }} ALL=(ALL) NOPASSWD: /usr/bin/zzz, /usr/bin/reboot, /usr/bin/poweroff'
        state: present
        validate: '/usr/sbin/visudo -cf %s'

    - name: Setup for removing unused firmware packages
      become: yes
      shell: |
        echo "ignorepkg=linux-firmware-amd" > /etc/xbps.d/10-ignore.conf &&
        echo "ignorepkg=linux-firmware-nvidia" > /etc/xbps.d/10-ignore.conf
